version: '3.6'
services:
  postgres:
    image: circleci/postgres:10.10
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: accounts-js-tests-e2e
  mongo:
    image: circleci/mongo:3
    ports:
      - '27017:27017'
  redis:
    image: circleci/redis:4
    ports:
      - '6379:6379'
