export const ServerHooks = {
  ValidateLogin: 'ValidateLogin',
  LoginSuccess: 'LoginSuccess',
  LoginError: 'LoginError',
  AuthenticateSuccess: 'AuthenticateSuccess',
  AuthenticateError: 'AuthenticateError',
  LogoutSuccess: 'LogoutSuccess',
  LogoutError: 'LogoutError',
  CreateUserSuccess: 'CreateUserSuccess',
  CreateUserError: 'CreateUserError',
  ResumeSessionSuccess: 'ResumeSessionSuccess',
  RefreshTokensSuccess: 'RefreshTokensSuccess',
  RefreshTokensError: 'RefreshTokensError',
  ImpersonationSuccess: 'ImpersonationSuccess',
  ImpersonationError: 'ImpersonationError',
  ResetPasswordSuccess: 'ResetPasswordSuccess',
  ChangePasswordSuccess: 'ChangePasswordSuccess',
};
