// flow-typed signature: 23ee46573c90172e6d9b6956dbd3a3be
// flow-typed version: <<STUB>>/crypto_v^0.0.3/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'crypto'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'crypto' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'crypto/md5' {
  declare module.exports: any;
}

declare module 'crypto/sha1' {
  declare module.exports: any;
}

declare module 'crypto/test/test-crypto' {
  declare module.exports: any;
}

// Filename aliases
declare module 'crypto/md5.js' {
  declare module.exports: $Exports<'crypto/md5'>;
}
declare module 'crypto/sha1.js' {
  declare module.exports: $Exports<'crypto/sha1'>;
}
declare module 'crypto/test/test-crypto.js' {
  declare module.exports: $Exports<'crypto/test/test-crypto'>;
}
