// flow-typed signature: fdeea983de3ae1e946ef0e1ebad92148
// flow-typed version: <<STUB>>/localstorage-polyfill_v^1.0.1/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'localstorage-polyfill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'localstorage-polyfill' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'localstorage-polyfill/localStorage' {
  declare module.exports: any;
}

declare module 'localstorage-polyfill/localStorage.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'localstorage-polyfill/localStorage.js' {
  declare module.exports: $Exports<'localstorage-polyfill/localStorage'>;
}
declare module 'localstorage-polyfill/localStorage.spec.js' {
  declare module.exports: $Exports<'localstorage-polyfill/localStorage.spec'>;
}
