export const EMAIL_ONLY_NO_PASSWORD = 'EMAIL_ONLY_NO_PASSWORD';
export const EMAIL_ONLY = 'EMAIL_ONLY';
export const USERNAME_AND_EMAIL = 'USERNAME_AND_EMAIL';
export const USERNAME_AND_OPTIONAL_EMAIL = 'USERNAME_AND_OPTIONAL_EMAIL';
export const USERNAME_ONLY = 'USERNAME_ONLY';
export const USERNAME_AND_EMAIL_NO_PASSWORD = 'USERNAME_AND_EMAIL_NO_PASSWORD';
