export const EMAIL_ONLY_NO_PASSWORD = Symbol('EMAIL_ONLY_NO_PASSWORD');
export const EMAIL_ONLY = Symbol('EMAIL_ONLY');
export const USERNAME_AND_EMAIL = Symbol('USERNAME_AND_EMAIL');
export const USERNAME_AND_OPTIONAL_EMAIL = Symbol('USERNAME_AND_OPTIONAL_EMAIL');
export const USERNAME_ONLY = Symbol('USERNAME_ONLY');
export const USERNAME_AND_EMAIL_NO_PASSWORD = Symbol('USERNAME_AND_EMAIL_NO_PASSWORD');
