// flow-typed signature: 4dab65669846aa8e40820ce231531287
// flow-typed version: <<STUB>>/crypto-js_v3.1.9-1/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'crypto-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'crypto-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'crypto-js/aes' {
  declare module.exports: any;
}

declare module 'crypto-js/cipher-core' {
  declare module.exports: any;
}

declare module 'crypto-js/core' {
  declare module.exports: any;
}

declare module 'crypto-js/crypto-js' {
  declare module.exports: any;
}

declare module 'crypto-js/enc-base64' {
  declare module.exports: any;
}

declare module 'crypto-js/enc-hex' {
  declare module.exports: any;
}

declare module 'crypto-js/enc-latin1' {
  declare module.exports: any;
}

declare module 'crypto-js/enc-utf16' {
  declare module.exports: any;
}

declare module 'crypto-js/enc-utf8' {
  declare module.exports: any;
}

declare module 'crypto-js/evpkdf' {
  declare module.exports: any;
}

declare module 'crypto-js/format-hex' {
  declare module.exports: any;
}

declare module 'crypto-js/format-openssl' {
  declare module.exports: any;
}

declare module 'crypto-js/hmac-md5' {
  declare module.exports: any;
}

declare module 'crypto-js/hmac-ripemd160' {
  declare module.exports: any;
}

declare module 'crypto-js/hmac-sha1' {
  declare module.exports: any;
}

declare module 'crypto-js/hmac-sha224' {
  declare module.exports: any;
}

declare module 'crypto-js/hmac-sha256' {
  declare module.exports: any;
}

declare module 'crypto-js/hmac-sha3' {
  declare module.exports: any;
}

declare module 'crypto-js/hmac-sha384' {
  declare module.exports: any;
}

declare module 'crypto-js/hmac-sha512' {
  declare module.exports: any;
}

declare module 'crypto-js/hmac' {
  declare module.exports: any;
}

declare module 'crypto-js/lib-typedarrays' {
  declare module.exports: any;
}

declare module 'crypto-js/md5' {
  declare module.exports: any;
}

declare module 'crypto-js/mode-cfb' {
  declare module.exports: any;
}

declare module 'crypto-js/mode-ctr-gladman' {
  declare module.exports: any;
}

declare module 'crypto-js/mode-ctr' {
  declare module.exports: any;
}

declare module 'crypto-js/mode-ecb' {
  declare module.exports: any;
}

declare module 'crypto-js/mode-ofb' {
  declare module.exports: any;
}

declare module 'crypto-js/pad-ansix923' {
  declare module.exports: any;
}

declare module 'crypto-js/pad-iso10126' {
  declare module.exports: any;
}

declare module 'crypto-js/pad-iso97971' {
  declare module.exports: any;
}

declare module 'crypto-js/pad-nopadding' {
  declare module.exports: any;
}

declare module 'crypto-js/pad-pkcs7' {
  declare module.exports: any;
}

declare module 'crypto-js/pad-zeropadding' {
  declare module.exports: any;
}

declare module 'crypto-js/pbkdf2' {
  declare module.exports: any;
}

declare module 'crypto-js/rabbit-legacy' {
  declare module.exports: any;
}

declare module 'crypto-js/rabbit' {
  declare module.exports: any;
}

declare module 'crypto-js/rc4' {
  declare module.exports: any;
}

declare module 'crypto-js/ripemd160' {
  declare module.exports: any;
}

declare module 'crypto-js/sha1' {
  declare module.exports: any;
}

declare module 'crypto-js/sha224' {
  declare module.exports: any;
}

declare module 'crypto-js/sha256' {
  declare module.exports: any;
}

declare module 'crypto-js/sha3' {
  declare module.exports: any;
}

declare module 'crypto-js/sha384' {
  declare module.exports: any;
}

declare module 'crypto-js/sha512' {
  declare module.exports: any;
}

declare module 'crypto-js/tripledes' {
  declare module.exports: any;
}

declare module 'crypto-js/x64-core' {
  declare module.exports: any;
}

// Filename aliases
declare module 'crypto-js/aes.js' {
  declare module.exports: $Exports<'crypto-js/aes'>;
}
declare module 'crypto-js/cipher-core.js' {
  declare module.exports: $Exports<'crypto-js/cipher-core'>;
}
declare module 'crypto-js/core.js' {
  declare module.exports: $Exports<'crypto-js/core'>;
}
declare module 'crypto-js/crypto-js.js' {
  declare module.exports: $Exports<'crypto-js/crypto-js'>;
}
declare module 'crypto-js/enc-base64.js' {
  declare module.exports: $Exports<'crypto-js/enc-base64'>;
}
declare module 'crypto-js/enc-hex.js' {
  declare module.exports: $Exports<'crypto-js/enc-hex'>;
}
declare module 'crypto-js/enc-latin1.js' {
  declare module.exports: $Exports<'crypto-js/enc-latin1'>;
}
declare module 'crypto-js/enc-utf16.js' {
  declare module.exports: $Exports<'crypto-js/enc-utf16'>;
}
declare module 'crypto-js/enc-utf8.js' {
  declare module.exports: $Exports<'crypto-js/enc-utf8'>;
}
declare module 'crypto-js/evpkdf.js' {
  declare module.exports: $Exports<'crypto-js/evpkdf'>;
}
declare module 'crypto-js/format-hex.js' {
  declare module.exports: $Exports<'crypto-js/format-hex'>;
}
declare module 'crypto-js/format-openssl.js' {
  declare module.exports: $Exports<'crypto-js/format-openssl'>;
}
declare module 'crypto-js/hmac-md5.js' {
  declare module.exports: $Exports<'crypto-js/hmac-md5'>;
}
declare module 'crypto-js/hmac-ripemd160.js' {
  declare module.exports: $Exports<'crypto-js/hmac-ripemd160'>;
}
declare module 'crypto-js/hmac-sha1.js' {
  declare module.exports: $Exports<'crypto-js/hmac-sha1'>;
}
declare module 'crypto-js/hmac-sha224.js' {
  declare module.exports: $Exports<'crypto-js/hmac-sha224'>;
}
declare module 'crypto-js/hmac-sha256.js' {
  declare module.exports: $Exports<'crypto-js/hmac-sha256'>;
}
declare module 'crypto-js/hmac-sha3.js' {
  declare module.exports: $Exports<'crypto-js/hmac-sha3'>;
}
declare module 'crypto-js/hmac-sha384.js' {
  declare module.exports: $Exports<'crypto-js/hmac-sha384'>;
}
declare module 'crypto-js/hmac-sha512.js' {
  declare module.exports: $Exports<'crypto-js/hmac-sha512'>;
}
declare module 'crypto-js/hmac.js' {
  declare module.exports: $Exports<'crypto-js/hmac'>;
}
declare module 'crypto-js/index' {
  declare module.exports: $Exports<'crypto-js'>;
}
declare module 'crypto-js/index.js' {
  declare module.exports: $Exports<'crypto-js'>;
}
declare module 'crypto-js/lib-typedarrays.js' {
  declare module.exports: $Exports<'crypto-js/lib-typedarrays'>;
}
declare module 'crypto-js/md5.js' {
  declare module.exports: $Exports<'crypto-js/md5'>;
}
declare module 'crypto-js/mode-cfb.js' {
  declare module.exports: $Exports<'crypto-js/mode-cfb'>;
}
declare module 'crypto-js/mode-ctr-gladman.js' {
  declare module.exports: $Exports<'crypto-js/mode-ctr-gladman'>;
}
declare module 'crypto-js/mode-ctr.js' {
  declare module.exports: $Exports<'crypto-js/mode-ctr'>;
}
declare module 'crypto-js/mode-ecb.js' {
  declare module.exports: $Exports<'crypto-js/mode-ecb'>;
}
declare module 'crypto-js/mode-ofb.js' {
  declare module.exports: $Exports<'crypto-js/mode-ofb'>;
}
declare module 'crypto-js/pad-ansix923.js' {
  declare module.exports: $Exports<'crypto-js/pad-ansix923'>;
}
declare module 'crypto-js/pad-iso10126.js' {
  declare module.exports: $Exports<'crypto-js/pad-iso10126'>;
}
declare module 'crypto-js/pad-iso97971.js' {
  declare module.exports: $Exports<'crypto-js/pad-iso97971'>;
}
declare module 'crypto-js/pad-nopadding.js' {
  declare module.exports: $Exports<'crypto-js/pad-nopadding'>;
}
declare module 'crypto-js/pad-pkcs7.js' {
  declare module.exports: $Exports<'crypto-js/pad-pkcs7'>;
}
declare module 'crypto-js/pad-zeropadding.js' {
  declare module.exports: $Exports<'crypto-js/pad-zeropadding'>;
}
declare module 'crypto-js/pbkdf2.js' {
  declare module.exports: $Exports<'crypto-js/pbkdf2'>;
}
declare module 'crypto-js/rabbit-legacy.js' {
  declare module.exports: $Exports<'crypto-js/rabbit-legacy'>;
}
declare module 'crypto-js/rabbit.js' {
  declare module.exports: $Exports<'crypto-js/rabbit'>;
}
declare module 'crypto-js/rc4.js' {
  declare module.exports: $Exports<'crypto-js/rc4'>;
}
declare module 'crypto-js/ripemd160.js' {
  declare module.exports: $Exports<'crypto-js/ripemd160'>;
}
declare module 'crypto-js/sha1.js' {
  declare module.exports: $Exports<'crypto-js/sha1'>;
}
declare module 'crypto-js/sha224.js' {
  declare module.exports: $Exports<'crypto-js/sha224'>;
}
declare module 'crypto-js/sha256.js' {
  declare module.exports: $Exports<'crypto-js/sha256'>;
}
declare module 'crypto-js/sha3.js' {
  declare module.exports: $Exports<'crypto-js/sha3'>;
}
declare module 'crypto-js/sha384.js' {
  declare module.exports: $Exports<'crypto-js/sha384'>;
}
declare module 'crypto-js/sha512.js' {
  declare module.exports: $Exports<'crypto-js/sha512'>;
}
declare module 'crypto-js/tripledes.js' {
  declare module.exports: $Exports<'crypto-js/tripledes'>;
}
declare module 'crypto-js/x64-core.js' {
  declare module.exports: $Exports<'crypto-js/x64-core'>;
}
