name: Node CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Test packages
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Master
        uses: actions/checkout@v4

      - name: Setup env
        uses: darkbasic/shared-config/setup@main
        with:
          nodeVersion: 18

      - name: Check lint
        run: yarn run test:lint

      - name: Compile packages
        run: yarn run compile

      - name: Docker compose
        run: docker-compose up -d

      - name: Run tests
        run: yarn run coverage

      - name: Upload coverage
        uses: codecov/codecov-action@v3

  test-examples:
    name: Test examples
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Master
        uses: actions/checkout@v4

      - name: Setup env
        uses: darkbasic/shared-config/setup@main
        with:
          nodeVersion: 18

      - name: Compile packages
        run: yarn run compile

      - name: Test examples
        run: yarn run test:examples
        env:
          REACT_APP_API_URL: http://localhost:3000

  test-documentation:
    name: Test documentation
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Master
        uses: actions/checkout@v4

      - name: Setup env
        uses: darkbasic/shared-config/setup@main
        with:
          nodeVersion: 18

      - name: Test documentation
        run: yarn workspace accounts-js run build
