name: website

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deployment:
    runs-on: ubuntu-22.04
    if: github.event.pull_request.head.repo.full_name == github.repository || github.event_name == 'push'
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: darkbasic/shared-config/setup@main
        name: setup env
        with:
          nodeVersion: 18
          packageManager: yarn

      - uses: darkbasic/shared-config/website-cf@main
        name: build and deploy website
        with:
          cloudflareApiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflareAccountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: accounts-js
          prId: ${{ github.event.pull_request.number }}
          websiteDirectory: ./
          buildScript: yarn compile && cd website && yarn build
          artifactDir: website/build
